repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: local
  hooks:
    - id: local-biome-check
      name: biome check
      entry: npx biome check --write --files-ignore-unknown=true --no-errors-on-unmatched
      language: system
      types: [text]
